#!/bin/bash

# Base-dir: dir where manual_lex.odt is located.
# Under here, there wil we a dir odt-unzipped after the first extraction
rm odt-unzipped/* -rf
unzip manual_lex.odt -d odt-unzipped

# Replace placeholders with actual data
sed -i "s/\[ruileenheid\]/Niksen/g" odt-unzipped/content.xml
sed -i "s/\[mailadres-admin\]/letsdb@home.nl/g" odt-unzipped/content.xml
sed -i "s/\[naam-ruilkring\]/Ruilkring \'s-Hertogenbosch e.o./g" odt-unzipped/content.xml
sed -i "s/\[website\]/www.niksvoorniks.nl/g" odt-unzipped/content.xml
sed -i "s/\[letsblad\]/NiksVoorNiks/g" odt-unzipped/content.xml
sed -i "s/\[letsbenaming\]/ruilkring/g" odt-unzipped/content.xml

# Copy specific pictures; overwrite the existing ones!
cp pictures/bossche-ruilkring/* odt-unzipped/Pictures

# Zip all files together
cd odt-unzipped
zip ../manual_lex-bossche-ruilkring.odt * -r
cd ..

exit

[ruileenheid]     
Moeren

[mailadres-admin] 
info@letskring.nl

[naam-ruilkring]  
Letskring Mallemoer Breda

[website]         
www.letskringbreda.nl/

[letsblad]        
Moergazetje

[letsbenaming]
LETS-kring

